//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "trades")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub id: u32,
    #[sea_orm(column_type = "Text")]
    pub symbol: String,
    #[sea_orm(column_type = "Text")]
    pub entry_price: String,
    #[sea_orm(column_type = "Text")]
    pub close_price: String,
    #[sea_orm(column_type = "Text")]
    pub direction: String,
    #[sea_orm(column_type = "Text")]
    pub quantity: String,
    #[sea_orm(column_type = "Text")]
    pub leverage: String,
    pub created_at: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
